### PR TITLE
Write installation guide

### PR DESCRIPTION
**Pull request by matyo91**

### CODE REVIEW

**Review by WebMamba — CHANGES_REQUESTED** [review]
You don't need npm here I already used AssetMapper. Here are the step to install the project: 
composer install

bin/console doctrine:database:create

bin/console doctrine:migration:migrate

bin/console doctrine:fixtures:load

bin/console tailwind:build

And just like that everything should be good

**Comment by matyo91** [comment]
Some how it doesn't work without npm https://flowbite.com/docs/getting-started/symfony/#install-flowbite

**Review by WebMamba — CHANGES_REQUESTED** [review]
You don't need a package.json, package.log, and a node_modules, just run : 
npm install flowbite.
https://symfony.com/bundles/TailwindBundle/current/index.html#tailwind-plugins

**Review by WebMamba — APPROVED** [review]

**Comment by WebMamba** [comment]
Thanks @matyo91! I hope this project will show you some cool stuff! 😁

**Pull request merged**
